version: '3'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoProjectFirst
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: always