version: '3.8'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres} -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-pharmadb}
    command: ["postgres", "-c", "log_statement=all"]

  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres-data: