# Generated by Django 3.1.12 on 2025-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название соединения')),
                ('formula', models.CharField(max_length=100, verbose_name='Химическая формула')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Соединение',
                'verbose_name_plural': 'Соединения',
            },
        ),
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100, verbose_name='Тип модели')),
                ('training_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обучения')),
                ('metrics', models.JSONField(verbose_name='Метрики модели')),
                ('dataset_info', models.TextField(verbose_name='Информация о наборе данных')),
            ],
            options={
                'verbose_name': 'Обучение модели',
                'verbose_name_plural': 'Обучения модели',
            },
        ),
    ]
