# Generated by Django 5.0.3 on 2024-04-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0002_housingdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingdata',
            options={'verbose_name': 'Таблица с данными', 'verbose_name_plural': 'Таблица с данными'},
        ),
    ]
